

<h6 class="text-white">Acessar suas turmas</h6>
<hr>
<style media="screen">
	.pointer{
		cursor: pointer;
	}



</style>



<div id="fundo" class="row col-md-12 m-0 p-0 ">



	<div id="card-turma" onclick="window.location='/dia?D=segunda-feira'" class="col-xl-3 col-md-7 mb-5 pointer ">
		<div class="card border-left-primary shadow h-100 py-2 col-md-10">
			<div class="card-body p-2">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<!--<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Dia</div>-->
						<div class="h5 mb-0 font-weight-bold text-gray-800">Suas Turmas</div>
						<!--<p class="m-0">Seg: 20:00 - 10:00</p>-->
					</div>
					<div class="col-auto">
						<i class="fas fa-calendar fa-2x text-gray-300"></i>
					</div>
				</div>
			</div>
		</div>
	</div>

<!--
	<div onclick="window.location='/dia?D=terça-feira'" class="col-xl-3 col-md-6 mb-5 pointer">
		<div class="card border-left-primary shadow h-100 py-2 col-md-10">
			<div class="card-body p-2">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Dia</div>
						<div class="h5 mb-0 font-weight-bold text-gray-800">Terça-feira</div>
						<p class="m-0">Seg: 20:00 - 10:00</p>
					</div>
					<div class="col-auto">
						<i class="fas fa-calendar fa-2x text-gray-300"></i>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div onclick="window.location='/dia?D=quarta-feira'" class="col-xl-3 col-md-6 mb-5 pointer">
		<div class="card border-left-primary shadow h-100 py-2 col-md-10">
			<div class="card-body p-2">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Dia</div>
						<div class="h5 mb-0 font-weight-bold text-gray-800">Quarta-feira</div>
						<p class="m-0">Seg: 20:00 - 10:00</p>
					</div>
					<div class="col-auto">
						<i class="fas fa-calendar fa-2x text-gray-300"></i>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div onclick="window.location='/dia?D=quinta-feira'" class="col-xl-3 col-md-6 mb-5 pointer">
		<div class="card border-left-primary shadow h-100 py-2 col-md-10">
			<div class="card-body p-2">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Dia</div>
						<div class="h5 mb-0 font-weight-bold text-gray-800">Quinta-feira</div>
						<p class="m-0">Seg: 20:00 - 10:00</p>
					</div>
					<div class="col-auto">
						<i class="fas fa-calendar fa-2x text-gray-300"></i>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div onclick="window.location='/dia?D=sexta-feira'" class="col-xl-3 col-md-6 mb-5 pointer">
		<div class="card border-left-primary shadow h-100 py-2 col-md-10">
			<div class="card-body p-2">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Dia</div>
						<div class="h5 mb-0 font-weight-bold text-gray-800">Sexta-feira</div>
						<p class="m-0">Seg: 20:00 - 10:00</p>
					</div>
					<div class="col-auto">
						<i class="fas fa-calendar fa-2x text-gray-300"></i>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div onclick="window.location='/dia?D=sabado'" class="col-xl-3 col-md-6 mb-5 pointer">
		<div class="card border-left-primary shadow h-100 py-2 col-md-10">
			<div class="card-body p-2">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
					<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Dia</div>
						<div class="h5 mb-0 font-weight-bold text-gray-800">Sabádo</div>
						<p class="m-0">Seg: 20:00 - 10:00</p>
					</div>
					<div class="col-auto">
						<i class="fas fa-calendar fa-2x text-gray-300"></i>
					</div>
				</div>
			</div>
		</div>
	</div>

-->
</div>
