  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script>
		function botao(num){
			$('#file-input'+num).trigger('click');
			$('#file-input'+num).change(function(){
				var nomeArquivo = $(this)[0].files[0].name;
				$('#p'+num).append(nomeArquivo);
					console.log(nomeArquivo)
			})
		}
		$(document).ready(function() {
				//$('.bu').on('click', function() {
					//  $('#file-input').trigger('click');
				//});
			var numero = 2;
			$("#add").click(()=>{
				$("#depois").before('<input name="arquivo'+numero+'" id="file-input'+numero+'"type="file" class="form-control mb-1 d-none"><div onclick="botao('+numero+')" class="col-md-2  mr-2 p-2 mt-2 mb-2 bg-white shadow  rounded"><i style="cursor:pointer;" id="button" class="fa fa-folder fa-3x text-warning"></i><p id="p'+numero+'" class="text-muted"></p></div>');
				numero++;
			});
		});
	</script>
<h6>
	<a class="text-info" href="/atividades?id_turma=<?= $_GET['id_turma'] ?>&&name=<?= $_GET['name'] ?>&&id_curso=<?= $_GET['id_curso'] ?>">Atividades liberadas</a>
	/ Cadastrar atividades para turmas de
</h6>
<hr>
<div class="container-fluid bg-white p-3 rounded">
	<form class="col-12" action="/cad_atividade" method="post" enctype="multipart/form-data">

		<input type="hidden" name="id_curso" value="<?= $_GET['id_curso'] ?>">

		<label for="titulo" class="mb-0"> <strong>Modulo</strong> </label>
		<select class="form-control col-md-5 mb-3" name="modulo">
			<?php foreach ($this->view->modulos as $modulo): ?>
				<?php if ($this->view->id_curso['subcategoria']==$modulo['subcategoria']): ?>
					<option value="<?= $modulo['id_modulo'] ?>"><?= $modulo['nome_modulo'] ?></option>
				<?php endif; ?>
			<?php endforeach; ?>
		</select>

		<input type="hidden" name="subcategoria" value="<?= $this->view->id_curso['subcategoria'] ?>">


		<input type="hidden" name="id_turma" value="<?= $_GET['id_turma'] ?>">
		<input type="hidden" name="nome_turma" value="<?= $_GET['name'] ?>">
		<input type="hidden" name="id_curso" value="<?= $_GET['id_curso'] ?>">

<style media="screen">

	.foorm{
		width:43%;
		position: relative;
		height: 65px;
		overflow: hidden;
		border-radius: 3px;
		box-shadow: 0px 0px 10px #dddddd;
	}

	.foorm input{
		width: 100%;
		height: 100%;
		color: ##282828;
		padding-top:20px;
		border:none;
		outline: none;
		font-size: 18pt;
	}

	.foorm label{
		position: absolute;
		bottom: -10px;
		left: 0%;
		width: 100%;
		height: 100%;
		pointer-events: none;
		border-bottom: 1px solid black;
		margin-left: 5px;
	}

	.foorm label::after{
		content: "";
		position: absolute;
		left: 0px;
		bottom:-1px;
		height: 100%;
		width: 100%;
		border-bottom: 5px solid #5fa8d3;
		transform: translateX(-105%);
		transition: transform 0.3s ease;
	}
	.content-name{
		position: absolute;
		bottom: 1px;
		left: 0px;
		transition: all 0.3s ease;
	}

	.foorm input:focus + .label-name .content-name,
	.foorm input:valid + .label-name .content-name{
		transform: translateY(-160%);
		font-size: 17px;
		color: #5fa8d3;
		font-weight: bold;
		margin-left: 2px;
	}


	.foorm input:focus +  .label-name::after, .foorm input:valid + .label-name::after{
		transform: translateX(-1%);
	}


</style>
<br>
<div class="foorm">
	<input spellcheck="false" required autocomplete="off" type="text" name="titulo" >
			<label for="titulo"  class="label-name">
					<span class="content-name">Titulo</span>
			</label>

</div>

<br><br>

			<label for="img" class="mb-0"><strong>Imagem de capa</strong></label>
			<input id="img" type="file" required class="form-control col-md-5 mb-3" name="img">

			<label for="description" class="mb-0">
				<span>Descrição</span>
			</label>
			<textarea class="form-control col-md-5" name="descricao" rows="3" ></textarea>
			<!--<input id="description" type="text" class="form-control col-5 mb-3" name="descricao" >-->

			<label for="arquivo" class="mb-0 mt-3 "><strong>Disponibilizar imagem para vizualização</strong></label>
			<input id="arquivo"  type="file" class="form-control col-md-5 mb-5" name="img_view" >

			<h5 class="m-0  ml-3">Adicionar arquivos para download</h5>

			<div class="row col-md-12 bg-white m-0">
			          <input id="file-input1"  type="file" name="arquivo1" class="form-control mb-1 d-none ">
			          <div onclick="botao(1)" class="col-md-2  mr-2 p-2 mt-2 mb-2 bg-white shadow  rounded">
			            <i style="cursor:pointer;" id="button" class="button fa fa-folder fa-3x text-warning"></i>
			            <p id="p1" class="text-muted"></p>
			          </div>

			          <span id="depois"></span>
			          <div id="add" class="col-md-2  mr-2 mt-2 mb-2 p-5 bg-primary justify-content-center d-flex rounded">
			            <i style="cursor:pointer;" id="button" class="fa fa-plus fa-3x text-white"></i>
			          </div>
			</div>


		<!--	<label for="arquivo" class="mb-0 mt-2"><strong>Disponibilizar arquivo para download</strong></label>
			<input id="arquivo" type="file" class="form-control col-md-5" name="arquivo" >-->

			<label for="video" class="mb-0 mt-3"><strong>Disponibilizar uma videoaula sobre o assunto</strong></label>
			<input id="video" autocomplete="off"  type="text" class="form-control col-md-5" name="video" >

			<label for="data" class="mb-0 mt-3"><strong>Data de entrega</strong></label>
			<input id="data" type="date" class="form-control col-md-5" name="data">


      <label for="video" class="mb-0 mt-3"><strong>Valor minimo de XP para está atividade</strong></label>
      <input id="video" autocomplete="off"  type="number" class="form-control col-md-2" name="xp_atividade" >

			<div class="col-12 m-0 p-4 bg-primary mt-3 justify-content-end d-flex">
					<button type="submit" class="btn btn-success">Cadastrar</button>
			</div>

	</form>
</div>
