
<h6><a class="text-info" href="/dash_aluno?sub=<?= $_GET['sub'] ?>">Home /</a> Aulas</h6>


<div class="row col-md-12 bg-white p-2 m-0 pt-2">
	<div class="row col-md-12 p-3 mb-3">
			<h4><?= $_GET['nomeModulo'] ?></h4>
	</div>

<?php if ($_GET['modulo']==17) { ?>
<div class="row col-md-12">
	<!--Bloco de repetição-->
	<div onclick="window.location='/questionario'" class="col-xl-3 col-md-6 mb-4 pointer">
		<div class="card border-left-primary shadow h-100 py-2  col-md-11">
			<div class="card-body p-2">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="h5 mb-0 font-weight-bold text-gray-800"></div>
						<p class="m-0">Questionário-1</p>
					</div>
					<div class="col-auto">
						<i class="fas fa-book fa-2x text-gray-300"></i>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--Bloco de repetição-->
	</div>
<?php } ?>


<?php
		$x=1;
		$i=1;
		foreach ($this->view->atividades	 as $atividade):
?>
	<?php if ($atividade['id_modulo']==$this->view->id_modulo): ?>



		<div style="cursor:pointer;"  class="card shadow mb-4 col-md-5 ml-2">
			<style media="screen">
				.number{
					position: absolute;
					margin-top: -20px;
					margin-left: -20px;
					border-radius: 50%;
					padding: 12px;
					padding-top: 32px;
					padding-left: 11px;
					width: 100px;
					height: 100px;
				}
				</style>

						<?php



								foreach ($this->view->atividadesRealizadas as  $AtividadeR):
								if($AtividadeR['id_atividade'] == $atividade['id_atividade']){
									$state = "success";
									break;
								}else{
									$state = "primary";
								}
								endforeach;
								if(count($this->view->atividadesRealizadas)==0){
									$state = "primary";
								}

							?>



							<div onclick="window.location='/ead?id_atividade=<?= $atividade['id_atividade'] ?>&&modulo=<?= $_GET['modulo'] ?>&&sub=<?= $_GET['sub'] ?>&&nomeModulo=<?= 	$_GET['nomeModulo'] ?>'" class="bg-<?= $state ?> justify-content-center d-flex number">
								<p style="font-size:13pt;" class="p-0 m-0 mt-1 text-white">Aula - <?= $i ?>  </p>
							</div>


			<div onclick="window.location='/ead?id_atividade=<?= $atividade['id_atividade'] ?>&&modulo=<?= $_GET['modulo'] ?>&&sub=<?= $_GET['sub'] ?>&&nomeModulo=<?= 	$_GET['nomeModulo'] ?>'" class="card-header py-3">
				<h6 style="margin-left:70px;" class=" font-weight-bold text-primary "><?= $atividade['titulo'] ?></h6>
			</div>
			<div class="card-body">

				<?php if ($atividade['video']==''): ?>
						<div class="text-center">
				<?php else: ?>
						<div  onclick="window.location='/ead?id_atividade=<?= $atividade['id_atividade'] ?>&&modulo=<?= $_GET['modulo'] ?>&&sub=<?= $_GET['sub'] ?>&&nomeModulo=<?= 	$_GET['nomeModulo'] ?>'" class="text-center">
				<?php endif; ?>
					<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width:25rem; " src="assets/dashboard/atividades/capa/<?= $atividade['img_cap'] ?>">
				</div>

				<p><?= $atividade['description'] ?></p>

				<div class="justify-content-end d-flex">

						<?php if($atividade['img_view']!=NULL){ ?>
					<button data-toggle="modal" data-target="#window<?= $x ?>" title="Ver imagem"  class="d-none d-sm-inline-block btn btn-sm btn-primary  ml-2 shadow-sm"><i class="fas fa-eye fa-sm text-white fa-1x"></i></button>
						<?php } ?>

							<?php if($atividade['arquivo']!=NULL){ ?>

							<a href="assets/dashboard/atividades/arquivo/<?= $atividade['arquivo'] ?>" title="Baixar" download="<?= $atividade['arquivo'] ?>" class="d-none ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
									<?php } ?>

									<?php if ($state=="primary"): ?>
										<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#entrega<?= $x; ?>"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> Entregar </button>
									<?php else: ?>
										<button class="btn btn-success  ml-2"  data-placement="top" title="Ver atividade que foi entregue"><i class="fas fa-eye fa-sm text-white fa-1x"></i> Ver Atividade </button>
									<?php endif; ?>


				</div>
			</div>
		</div>

		<div id="window<?= $x ?>" class="modal fade bd-example-modal-xl " tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-xl">
				<div class="modal-content">
					<div class="row col-md-12 p-2 m-0 bg-dark">
						<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 100rem;" src="assets/dashboard/atividades/view/<?= $atividade['img_view'] ?>">
					</div>
				</div>
			</div>
		</div>

		<div id="entrega<?= $x ?>" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="row col-md-12 p-3 bg-white m-0  rounded">
						<h6>Entregar trabalho - <?= $atividade['titulo'] ?></h6>

						<div class="row col-md-12 m-0 bg-white p-2">
							<form class="col-md-12" action="/entrega" method="post" enctype="multipart/form-data" onsubmit="return valida(this)">
								<input class="form-control mb-3" type="file" required name="arquivo">
								<input type="hidden" name="nomeTrabalho" value="<?= $atividade['titulo'] ?>">
								<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
								<input type="hidden" name="id_modulo" value="<?= $_GET['modulo'] ?>">
								<input type="hidden" name="id_atividade" value="<?= $atividade['id_atividade'] ?>">
								<button type="submit" class="btn btn-success ml-2" name="button"><i class="fas fa-hand-holding m-0"></i> Entregar </button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>


	<?php $i++; endif; ?>
<?php
		$x++;
	endforeach;
?>
</div>
