<div class="container-fluid">
	<h6><a class="text-info" href="">Home / </a> Entregar trabalhos</h6>
	<h1>danilo</h1>
	<form class="col-md-12 bg-white" action="/entrega" method="post" enctype="multipart/form-data">

		<label for="modulo" class="mb-0 mt-3"> <strong> Modulo</strong></label>
		<select id="modulo" class="form-control col-md-3 mt-0" name="id_modulo">
			<?php foreach ($this->view->modulo as $modulo): ?>
				<option value="<?= $modulo['id_modulo'] ?>"><?= $modulo['nome_modulo'] ?></option>
				<?php endforeach; ?>
		</select>

		<labelclass="mt-3 mb-0"><strong>Descrição</strong></label>
		<input type="text" class="form-control col-md-5" name="nomeTrabalho">

		<label class="mt-3 mb-0"><strong>Arquivo</strong></label>
		<input type="file" class="form-control col-md-5" name="arquivo">

		<div class="col-md-12 p-2 mt-3 justify-content-end d-flex bg-primary">
			<button type="submit" class="btn btn-success">Enviar</button>
		</div>


	</form>



</div>
