<h6><a href="/dash_aluno">HOME/ </a><a href="/windows">Exercícios/ </a>Exercício-1 </h6>

<div class="row col-md-12 bg-white p-2 m-0">

	<div class="card shadow mb-4 col-md-5 ml-2">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Criando um currículo no wordpad</h6>
		</div>
		<div class="card-body">
			<div class="text-center">
				<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/wordpad/wordpad.png">
			</div>

			<p>Aprenda criar um currículo na ferramenta wordpad</p>

			<div class="justify-content-end d-flex">

					<button data-toggle="modal" data-target="#curriculo" title="Ver imagem"  class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-eye fa-sm text-white fa-1x"></i></button>

						<a href="assets/dashboard/img/wordpad/wordpad2.png" title="Baixar" download="img/wordpad/wordpad2.png" class="d-none ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>

						<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#entrega" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
			</div>
		</div>
	</div>

	<div id="curriculo" class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-xl">
			<div class="modal-content">
				<div class="row col-md-12 p-2 m-0 bg-dark">
					<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 100rem;" src="assets/dashboard/img/wordpad/wordpad2.png">
				</div>
			</div>
		</div>
	</div>


	<!-- Large modal -->
<div id="entrega" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		<div class="row col-md-12 p-3 bg-white m-0  rounded">
			<h6>Entregar trabalho </h6>

			<div class="row col-md-12 m-0 bg-white p-2">
				<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
					<input class="form-control mb-3" type="file" name="arquivo">
					<input type="hidden" name="nomeTrabalho" value="Curriculo WordPad">
					<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
							<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>
</div>











</div>
