<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<div class="d-sm-flex align-items-center justify-content-between mb-4">
		<h1 class="h3 mb-0 text-gray-800">Assistente administrativo</h1>
		<!--<a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>-->
	</div>

	<div class="row">

		<div style="cursor:pointer;" onclick="window.location='/dash_aluno?sub=D'"  class=" shadow  col-md-3 ml-2 col-sm-12 mb-3 rounded">
			<div class=" py-3 m-0 p-0">
				<h6 class="m-0 font-weight-bold text-primary mt-3">Desenvolvimento pessoal</h6>
			</div>
			<div class="card-body m-0 p-0">
				<p class="mb-2">Prof: Lidiane</p>
				<!--<i class="fas fa-folder fa-2x text-warning mt-0 "></i><p class="mb-3">5 Trabalhos pendentes</p>-->
			</div>
		</div>

		<div style="cursor:pointer;" onclick="window.location='/dash_aluno?sub=A'"  class=" shadow  col-md-3 ml-2 col-sm-12 mb-3 rounded">
			<div class=" py-3 m-0 p-0">
				<h6 class="m-0 font-weight-bold text-primary mt-3">Administrativo</h6>
			</div>
			<div class="card-body m-0 p-0">
				<p class="mb-2">Prof: Sergio</p>
				<!--<i class="fas fa-folder fa-2x text-warning mt-0"></i><p class="mb-3">5 Trabalhos pendentes</p>-->
			</div>
		</div>

		<div style="cursor:pointer;" onclick="window.location='/dash_aluno?sub=T'" class=" shadow  col-md-3 ml-2 col-sm-12 mb-3 rounded">
			<div class=" py-3 m-0 p-0">
				<h6 class="m-0 font-weight-bold text-primary mt-3">Desenvolvimento tecnológico</h6>
			</div>
			<div class="card-body m-0 p-0">
				<p class="mb-2">Prof: Danilo</p>
				<!--<i class="fas fa-folder fa-2x text-warning mt-0"></i><p class="mb-3">5 Trabalhos pendentes</p>-->
			</div>
		</div>



<!--

		<div onclick="window.location='/v_atividades?modulo=1'" class="card shadow mb-4 col-md-4 ml-2">
			<div class="card-header py-3">
				<h6 class="m-0 font-weight-bold text-primary">Word</h6>
			</div>
			<div class="card-body">
				<div class="text-center">
					<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 30rem;" src="assets/dashboard/img/word/word.jpg">
				</div>

				<p>Aprenda a utilizar todos os recursos do Word</p>

				<div class="justify-content-end d-flex">
						<a href="/v_atividades?modulo=1" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">Entrar</a>
				</div>
			</div>
		</div>



		<div class="card shadow mb-4 col-md-4 ml-2">
			<div class="card-header py-3">
				<h6 class="m-0 font-weight-bold text-primary">Windows10</h6>
			</div>
			<div class="card-body">
				<div class="text-center">
					<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 30rem;" src="assets/dashboard/img/pages/win.jpg">
				</div>

				<p>Aprenda a utilizar todos os recursos do windows10</p>

				<div class="justify-content-end d-flex">
						<a href="/windows" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">Entrar</a>
				</div>
			</div>
		</div>





-->
	</div>
<!--
	<div class="row col-md-12 bg-white m-0  pt-3 pb-5 mb-5">
		<div class="row col-md-12">
			<h4 class="ml-2 mb-4">Módulos concluidos</h4>
		</div>

		<div class="card shadow mb-4 col-md-2 ml-2 p-0">
			<div class="card-header py-3 ">
				<h6 class="m-0 font-weight-bold text-primary text-center">Word</h6>
			</div>
			<div class="card-body p-0 m-0">
				<div class="text-center p-0 m-0">
					<img class="img-fluid px-3 px-sm-4 mt-3 mb-4 m-0" style="width: 10rem;" src="assets/dashboard/img/word/word.jpg">
				</div>
			</div>
		</div>
	</div>
-->


<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
	<h5 class="modal-title" id="exampleModalLabel">Sair do painel?</h5>
	<button class="close" type="button" data-dismiss="modal" aria-label="Close">
		<span aria-hidden="true">×</span>
	</button>
</div>
<div class="modal-body">Selecione "Sair" Abaixo caso deseje realmente sair.</div>
<div class="modal-footer">
	<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
	<a class="btn btn-primary" href="/logout">Sair</a>
</div>
</div>
</div>
</div>

</div>
