<h6><a class="text-info" href="/dash_aluno">Home /</a> Photoshop</h6>

<div class="row col-md-12 bg-white p-2 m-0">



	<div class="card shadow mb-4 col-md-5 ml-2">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Exercicío [Melhorando iluminação]</h6>
		</div>
		<div class="card-body">
			<div class="text-center">
				<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/parque.jpg">
			</div>

			<p>Utilizando a ferramenta de iluminação melhore a qualidade desta imagem</p>

			<div class="justify-content-end d-flex">

						<a href="assets/dashboard/img/photoshop/parque.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>

							<!--<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#entrega"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>-->
			</div>
		</div>
	</div>


	<div class="card shadow mb-4 col-md-5 ml-2">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Exercicío [Melhorando iluminação]</h6>
		</div>
		<div class="card-body">
			<div class="text-center">
				<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/parque2.jpg">
			</div>

			<p>Utilizando a ferramenta de iluminação melhore a qualidade desta imagem</p>

			<div class="justify-content-end d-flex">

						<a href="assets/dashboard/img/photoshop/parque2.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>

							<!--<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#entrega"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>-->
			</div>
		</div>
	</div>

<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Ferramenta de recorte</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/recorte.jpg">
		</div>

		<p>Aprendendo a utilizar a ferramenta de recorte.</p>

		<div class="justify-content-end d-flex">
				<button data-toggle="modal" title="ver imagem" data-target="#photo1"  class="d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-eye fa-sm text-white"></i></button>

					<a href="assets/dashboard/img/photoshop/recorte.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>

						<!--<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#entrega"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>-->
		</div>
	</div>
</div>

<div id="photo1" class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-xl">
		<div class="modal-content">
			<div class="row col-md-12 p-2 m-0 bg-dark">
				<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 190rem;" src="assets/dashboard/img/photoshop/recorte.jpg">
			</div>
		</div>
	</div>
</div>


<!--=============================================imagem um===============================================================-->



<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Treinando ferramenta de recorte</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/recorte2.jpg">
		</div>

		<p>Aprendendo a utilizar a ferramenta de recorte.</p>

		<div class="justify-content-end d-flex">
				<button data-toggle="modal" title="ver imagem" data-target="#photo2"  class="d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-eye fa-sm text-white"></i></button>

					<a href="assets/dashboard/img/photoshop/recorte2.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>

						<!--<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#entrega"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>-->
		</div>
	</div>
</div>


<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Exercicío 3 [Borracha mágica]</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/fundo.jpg">
		</div>
		<p>Utilizando a ferramenta do photoshop [Borracha mágica] retire o fundo preto deixando apenas a flor</p>
		<div class="justify-content-end d-flex">
					<a href="assets/dashboard/img/photoshop/fundo.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
		</div>
	</div>
</div>


<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Exercicío 4 [Borracha mágica]</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/fundo1.jpg">
		</div>
		<p>Utilizando a ferramenta do photoshop [Borracha mágica] retire o fundo preto deixando apenas o notebook</p>
		<div class="justify-content-end d-flex">
					<a href="assets/dashboard/img/photoshop/fundo1.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
		</div>
	</div>
</div>


<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Exercicío 5 [Ferramentas de recorte]</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/fe_recorte.jpg">
		</div>
		<p>Utilizando alguma ferramenta de recorte do photoshop deixe apenas o passaro visivel com o fundo transparente</p>
		<div class="justify-content-end d-flex">
					<a href="assets/dashboard/img/photoshop/fe_recorte.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
		</div>
	</div>
</div>


<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Exercicío 6 [Ferramentas de recorte]</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/fe_recorte1.jpg">
		</div>
		<p>Utilizando alguma ferramenta de recorte do photoshop deixe apenas a lampada visivel</p>
		<div class="justify-content-end d-flex">
					<a href="assets/dashboard/img/photoshop/fe_recorte1.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
		</div>
	</div>
</div>


<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Exercicío 7 [Ferramentas de recorte]</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/fe_recorte2.jpg">
		</div>
		<p>Utilizando alguma ferramenta de recorte do photoshop deixe apenas o tucano visivel</p>
		<div class="justify-content-end d-flex">
					<a href="assets/dashboard/img/photoshop/fe_recorte2.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
		</div>
	</div>
</div>

<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Exercicío 8 [Ferramenta seleção rápida]</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/ceu.jpg">
		</div>
		<p>Utilizando a ferramenta de [seleção rápida] substitua o céu da imagem</p>
		<div class="justify-content-end d-flex">
					<a href="assets/dashboard/img/photoshop/ceu.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
		</div>
	</div>
</div>


<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Exercicío 9 [Ferramenta seleção rápida]</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/ceu1.jpg">
		</div>
		<p>Utilizando a ferramenta de [seleção rápida] deixe apenas a flor na imagem.</p>
		<div class="justify-content-end d-flex">
					<a href="assets/dashboard/img/photoshop/ceu1.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
		</div>
	</div>
</div>



<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Exercicío 11 [Sensível a conteúdo]</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/barco.jpeg">
		</div>
		<p>Utilizando seu conhecimento em photoshop retire os dois barcos da imagem.</p>
		<div class="justify-content-end d-flex">
					<a href="assets/dashboard/img/photoshop/barco.jpeg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
		</div>
	</div>
</div>


<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Exercicío 12 [Sensível a conteúdo]</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/sensivel.jpeg">
		</div>
		<p>Utilizando seu conhecimento em photoshop retire a mulher da imagem .</p>
		<div class="justify-content-end d-flex">
					<a href="assets/dashboard/img/photoshop/sensivel.jpeg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
		</div>
	</div>
</div>



<div class="card shadow mb-4 col-md-5 ml-2">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Exercicío 14 [Distorção de marionete]</h6>
	</div>
	<div class="card-body">
		<div class="text-center">
			<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/photoshop/arvore_torta.jpg">
		</div>
		<p>Utilizando seu conhecimento em photoshop desentorte a árvore.</p>
		<div class="justify-content-end d-flex">
					<a href="assets/dashboard/img/photoshop/arvore_torta.jpg" title="Baixar" download="" class="ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>
		</div>
	</div>
</div>










































</div>
