<h6><a class="text-info" href="/dash_aluno">Home / </a><a class="text-info" href="/windows">Exercícios</a> / Programas auxiliares do windows-10 </h6>

 <center class="mt-5"><h5>Praticando para apender</h5><center>

<div class="container">
	<div class="row col-md-12 bg-white p-3 m-0">





		<!--=========================================================questao um===================================================-->
				<div class="card shadow mb-4 col-md-5 ml-2">
					<div class="card-header py-3">
						<h6 class="m-0 font-weight-bold text-primary text-left">Praticando conceitos</h6>
					</div>
					<div class="card-body">
						<p class="text-left">1) Imagine que você precise criar um lembrete em seu computador e para isto irá usar um programa nativo do windows-10, abra este programa digite seu lembrete e depois tire um print da tela e envie-o pelo campo abaixo</p>
						<div class="justify-content-end d-flex">
									<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#questao1" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
						</div>
					</div>
				</div>


				<!-- Large modal -->
			<div id="questao1" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="row col-md-12 p-3 bg-white m-0  rounded">
						<h6>Entregar Questão 1 - Lembrete</h6>

						<div class="row col-md-12 m-0 bg-white p-2">
							<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
								<input class="form-control mb-3" type="file" name="arquivo">
								<input type="hidden" name="nomeTrabalho" value="Questão 1 - Lembrete">
								<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
										<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
								</div>

							</form>
						</div>
					</div>
				</div>
			</div>
			</div>
		<!--========================================================= fim questao 1===================================================-->



				<!--=========================================================questao dois===================================================-->
						<div class="card shadow mb-4 col-md-5 ml-2">
							<div class="card-header py-3">
								<h6 class="m-0 font-weight-bold text-primary text-left">Praticando conceitos</h6>
							</div>
							<div class="card-body">
								<p class="text-left">2) Imagine que você está em seu trabalho e lhe aparece a necessidade de converter $100 dólares em real, abra um programa nativo do windows faça está conversão e envie um print pelo campo abaixo.</p>
								<div class="justify-content-end d-flex">
											<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#questao2" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
								</div>
							</div>
						</div>


						<!-- Large modal -->
					<div id="questao2" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
					<div class="modal-dialog modal-lg">
						<div class="modal-content">
							<div class="row col-md-12 p-3 bg-white m-0  rounded">
								<h6>Entregar Questão 2 - Conversão</h6>

								<div class="row col-md-12 m-0 bg-white p-2">
									<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
										<input class="form-control mb-3" type="file" name="arquivo">
										<input type="hidden" name="nomeTrabalho" value="Questão 2 - Conversão">
										<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
												<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
										</div>

									</form>
								</div>
							</div>
						</div>
					</div>
					</div>
				<!--========================================================= fim questao dois===================================================-->


								<!--=========================================================questao três===================================================-->
										<div class="card shadow mb-4 col-md-5 ml-2">
											<div class="card-header py-3">
												<h6 class="m-0 font-weight-bold text-primary text-left">Praticando conceitos</h6>
											</div>
											<div class="card-body">
												<p class="text-left"> 3) Imagine que você precise editar um texto simples mas seu computador é novo e ainda não há o programa word instalado tendo em vista isto abra um programa nativo do windows para edição de texto digite seu nome e envie o print pelo campo abaixo.</p>
												<div class="justify-content-end d-flex">
															<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#questao3" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
												</div>
											</div>
										</div>


										<!-- Large modal -->
									<div id="questao3" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
									<div class="modal-dialog modal-lg">
										<div class="modal-content">
											<div class="row col-md-12 p-3 bg-white m-0  rounded">
												<h6>Entregar Questão 3 - Edição de texto</h6>

												<div class="row col-md-12 m-0 bg-white p-2">
													<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
														<input class="form-control mb-3" type="file" name="arquivo">
														<input type="hidden" name="nomeTrabalho" value="Questão 3 - Edição de texto">
														<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
																<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
														</div>

													</form>
												</div>
											</div>
										</div>
									</div>
									</div>
								<!--========================================================= fim questao tres===================================================-->



								<!--=========================================================questao quatro===================================================-->
										<div class="card shadow mb-4 col-md-5 ml-2">
											<div class="card-header py-3">
												<h6 class="m-0 font-weight-bold text-primary text-left">Praticando conceitos</h6>
											</div>
											<div class="card-body">
												<p class="text-left">4) Imagine que você está em seu trabalho e lhe aparece a necessidade de fazer uma anotação rápida porém você está sem nenhum papel por perto apenas o computador está aberto em sua frente, tendo em vista está situação abra um programa nativo do windows para fazer uma anotação e envie um print da anotação no campo abaixo.</p>
												<div class="justify-content-end d-flex">
															<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#questao4" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
												</div>
											</div>
										</div>


										<!-- Large modal -->
									<div id="questao4" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
									<div class="modal-dialog modal-lg">
										<div class="modal-content">
											<div class="row col-md-12 p-3 bg-white m-0  rounded">
												<h6>Entregar Questão 4 - Anotação</h6>

												<div class="row col-md-12 m-0 bg-white p-2">
													<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
														<input class="form-control mb-3" type="file" name="arquivo">
														<input type="hidden" name="nomeTrabalho" value="Questão 4 - Anotação ">
														<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
																<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
														</div>

													</form>
												</div>
											</div>
										</div>
									</div>
									</div>
								<!--========================================================= fim questao quatro===================================================-->



								<!--=========================================================questao cinco===================================================-->
										<div class="card shadow mb-4 col-md-5 ml-2">
											<div class="card-header py-3">
												<h6 class="m-0 font-weight-bold text-primary text-left">Praticando conceitos</h6>
											</div>
											<div class="card-body">
												<p class="text-left">5) Imagine que a empresa em que você trabalha acabou de comprar uma impressora nova e a deixou em sua sala, tendo em vista está situção agora você precisa instala-la vá até as configurações do windows onde você poderia fazer a conecção com a impressora e envie um print da tela quando chegar neste ponto.</p>
												<div class="justify-content-end d-flex">
															<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#questao5" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
												</div>
											</div>
										</div>


										<!-- Large modal -->
									<div id="questao5" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
									<div class="modal-dialog modal-lg">
										<div class="modal-content">
											<div class="row col-md-12 p-3 bg-white m-0  rounded">
												<h6>Entregar Questão 5 - Conectando a impressora</h6>

												<div class="row col-md-12 m-0 bg-white p-2">
													<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
														<input class="form-control mb-3" type="file" name="arquivo">
														<input type="hidden" name="nomeTrabalho" value="Questão 5 - Impressora">
														<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
																<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
														</div>

													</form>
												</div>
											</div>
										</div>
									</div>
									</div>
								<!--========================================================= fim questao cinco===================================================-->



						<!--=========================================================questao seis===================================================-->
																		<div class="card shadow mb-4 col-md-5 ml-2">
																			<div class="card-header py-3">
																				<h6 class="m-0 font-weight-bold text-primary text-left">Praticando conceitos</h6>
																			</div>
																			<div class="card-body">
																				<p class="text-left">6) Tire um print do seu explorador de arquivos e envie pelo campo abaixo.</p>
																				<div class="justify-content-end d-flex pt-5">
																							<button class="btn btn-warning  ml-2 mt-5" data-toggle="modal" data-target="#questao6" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
																				</div>
																			</div>
																		</div>


																		<!-- Large modal -->
																	<div id="questao6" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
																	<div class="modal-dialog modal-lg">
																		<div class="modal-content">
																			<div class="row col-md-12 p-3 bg-white m-0  rounded">
																				<h6>Entregar Questão 6 - Explorador de arquivos </h6>

																				<div class="row col-md-12 m-0 bg-white p-2">
																					<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
																						<input class="form-control mb-3" type="file" name="arquivo">
																						<input type="hidden" name="nomeTrabalho" value="Questão 6 - explorador de arquivos">
																						<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
																								<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0 "></i> Entregar </button>
																						</div>

																					</form>
																				</div>
																			</div>
																		</div>
																	</div>
																	</div>
							<!--========================================================= fim questao seis===================================================-->


													<!--=========================================================questao sete===================================================-->
																									<div class="card shadow mb-4 col-md-5 ml-2">
																										<div class="card-header py-3">
																											<h6 class="m-0 font-weight-bold text-primary text-left">Praticando conceitos</h6>
																										</div>
																										<div class="card-body">
																											<p class="text-left">7) Dentro da pasta imagens do seu explorador de arquivos crie uma pasta com seu nome depois vá na internet pesquise uma imagem de céu salve está imagem dentro da pasta em que você criou, após ter feito este processo abra a pasta onde você salvou a imagem coloque os icones como grandes tire um print da tela e envie pelo campo abaixo.</p>
																											<div class="justify-content-end d-flex">
																														<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#questao7" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
																											</div>
																										</div>
																									</div>


																									<!-- Large modal -->
																								<div id="questao7" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
																								<div class="modal-dialog modal-lg">
																									<div class="modal-content">
																										<div class="row col-md-12 p-3 bg-white m-0  rounded">
																											<h6>Entregar Questão 7 - Salvar imagem</h6>

																											<div class="row col-md-12 m-0 bg-white p-2">
																												<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
																													<input class="form-control mb-3" type="file" name="arquivo">
																													<input type="hidden" name="nomeTrabalho" value="Questão 7 - Salvar imagem">
																													<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
																															<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
																													</div>

																												</form>
																											</div>
																										</div>
																									</div>
																								</div>
																								</div>
														<!--========================================================= fim questao sete===================================================-->


														<!--=========================================================questao oito===================================================-->
																										<div class="card shadow mb-4 col-md-5 ml-2">
																											<div class="card-header py-3">
																												<h6 class="m-0 font-weight-bold text-primary text-left">Praticando conceitos</h6>
																											</div>
																											<div class="card-body">
																												<p class="text-left mb-5 ">8) Vá até a configuração onde você poderia desinstalar um programa e envie um print pelo campo abaixo.</p>
																												<div class="justify-content-end d-flex pt-4">
																															<button class="btn btn-warning  ml-2 mt-5" data-toggle="modal" data-target="#questao8" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
																												</div>
																											</div>
																										</div>


																										<!-- Large modal -->
																									<div id="questao8" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
																									<div class="modal-dialog modal-lg">
																										<div class="modal-content">
																											<div class="row col-md-12 p-3 bg-white m-0  rounded">
																												<h6>Entregar Questão 8 - Desisntalar</h6>

																												<div class="row col-md-12 m-0 bg-white p-2">
																													<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
																														<input class="form-control mb-3" type="file" name="arquivo">
																														<input type="hidden" name="nomeTrabalho" value="Questão 8 - Desinstalar ">
																														<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
																																<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
																														</div>

																													</form>
																												</div>
																											</div>
																										</div>
																									</div>
																									</div>
															<!--========================================================= fim questao oito===================================================-->

<div class="row col-12">
			<!--=========================================================questao nove===================================================-->
																											<div class="card shadow mb-4 col-md-5 ml-2">
																												<div class="card-header py-3">
																													<h6 class="m-0 font-weight-bold text-primary text-left">Praticando conceitos</h6>
																												</div>
																												<div class="card-body">
																													<p class="text-left mb-5 ">9) Imaginando que o navegador de internet google chrome não estivesse querendo fechar abra o programa nativo do windows que forçaria o fechamento dele e  envie um print pelo campo abaixo.</p>
																													<div class="justify-content-end d-flex">
																																<button class="btn btn-warning  ml-2 " data-toggle="modal" data-target="#questao9" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
																													</div>
																												</div>
																											</div>


																											<!-- Large modal -->
																										<div id="questao9" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
																										<div class="modal-dialog modal-lg">
																											<div class="modal-content">
																												<div class="row col-md-12 p-3 bg-white m-0  rounded">
																													<h6>Entregar Questão 9 - Fechar Programa</h6>

																													<div class="row col-md-12 m-0 bg-white p-2">
																														<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
																															<input class="form-control mb-3" type="file" name="arquivo">
																															<input type="hidden" name="nomeTrabalho" value="Questão 9 - Fechar Programa">
																															<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
																																	<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
																															</div>

																														</form>
																													</div>
																												</div>
																											</div>
																										</div>
																										</div>
						<!--========================================================= fim questao nove===================================================-->
</div>











<!--=========================================================item um===================================================-->
		<div class="card shadow mb-4 col-md-5 ml-2">
			<div class="card-header py-3">
				<h6 class="m-0 font-weight-bold text-primary">Criando um controle de estoque no Google-planilhas</h6>
			</div>
			<div class="card-body">
				<div class="text-center">
					<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/Google/planilha.png">
				</div>

				<p>Aprenda criar um controle de estoque no google planilhas</p>

				<div class="justify-content-end d-flex">

						<button data-toggle="modal" data-target="#curriculo" title="Ver imagem"  class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-eye fa-sm text-white fa-1x"></i></button>

							<a href="assets/dashboard/img/Google/planilha.png" title="Baixar" download="" class="d-none ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>

							<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#entrega" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
				</div>
			</div>
		</div>



		<div id="curriculo" class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-xl">
				<div class="modal-content">
					<div class="row col-md-12 p-2 m-0 bg-dark">
						<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 100rem;" src="assets/dashboard/img/Google/planilha.png">
					</div>
				</div>
			</div>
		</div>



	<div id="entrega" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="row col-md-12 p-3 bg-white m-0  rounded">
				<h6>Entregar trabalho - Controle de estoque </h6>

				<div class="row col-md-12 m-0 bg-white p-2">
					<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
						<input class="form-control mb-3" type="file" name="arquivo">
						<input type="hidden" name="nomeTrabalho" value="Controle de estoque">
						<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
								<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
						</div>

					</form>
				</div>
			</div>
		</div>
	</div>
	</div>
<!--========================================================= fim item um===================================================-->


<!--=========================================================item dois===================================================-->
		<div class="card shadow mb-4 col-md-5 ml-2">
			<div class="card-header py-3">
				<h6 class="m-0 font-weight-bold text-primary">Criando uma carta de aviso no Google documentos</h6>
			</div>
			<div class="card-body">
				<div class="text-center">
					<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="assets/dashboard/img/Google/carta-presentation.png">
				</div>

				<p>Aprenda a criar uma carta de aviso no utilizando o Google doc</p>

				<div class="justify-content-end d-flex">

						<button data-toggle="modal" data-target="#carta" title="Ver imagem"  class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-eye fa-sm text-white fa-1x"></i></button>

							<a href="assets/dashboard/img/Google/carta.png" title="Baixar" download="" class="d-none ml-2 d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white 50"></i></a>

							<button class="btn btn-warning  ml-2" data-toggle="modal" data-target="#entregaCarta" title="Entregar atividade"  data-placement="top" title="Entregar atividade"><i class="fas fa-hand-holding"></i> </button>
				</div>
			</div>
		</div>



		<div id="carta" class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-xl">
				<div class="modal-content">
					<div class="row col-md-12 p-2 m-0 bg-dark">
						<img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 100rem;" src="assets/dashboard/img/Google/carta.png">
					</div>
				</div>
			</div>
		</div>



	<div id="entregaCarta" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="row col-md-12 p-3 bg-white m-0  rounded">
				<h6>Entregar trabalho - Carta no Google - Docs </h6>

				<div class="row col-md-12 m-0 bg-white p-2">
					<form class="col-md-12" action="/entrega	" method="post" enctype="multipart/form-data">
						<input class="form-control mb-3" type="file" name="arquivo">
						<input type="hidden" name="nomeTrabalho" value="Carta no Google-Docs">
						<div class="row col-md-12 bg-white p-2 justify-content-end m-0 ml-2">
								<button type="submit" class="btn btn-success ml-2" name="button" ><i class="fas fa-hand-holding m-0"></i> Entregar </button>
						</div>

					</form>
				</div>
			</div>
		</div>
	</div>
	</div>
<!--========================================================= fim item dois===================================================-->






	</div>
</div>
