<h6><a href="/dash_aluno">Home/</a> Exercícios </h6>
<style media="screen">
	.pointer{
		cursor: pointer;
	}
</style>
<div class="container">
		<div class="row col-md-12 bg-white p-2 m-0">

				<!--Bloco de repetição-->
				<div onclick="window.location='/exc1'" class="col-xl-3 col-md-6 mb-4 pointer">
					<div class="card border-left-primary shadow h-100 py-2  col-md-11">
						<div class="card-body p-2">
							<div class="row no-gutters align-items-center">
								<div class="col mr-2">
									<div class="h5 mb-0 font-weight-bold text-gray-800"></div>
									<p class="m-0">Exercício-1</p>
								</div>
								<div class="col-auto">
									<i class="fas fa-book fa-2x text-gray-300"></i>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--Bloco de repetição-->

				<!--Bloco de repetição-->
				<div onclick="window.location='/questionario'" class="col-xl-3 col-md-6 mb-4 pointer">
					<div class="card border-left-primary shadow h-100 py-2  col-md-11">
						<div class="card-body p-2">
							<div class="row no-gutters align-items-center">
								<div class="col mr-2">
									<div class="h5 mb-0 font-weight-bold text-gray-800"></div>
									<p class="m-0">Exercicio-2</p>
								</div>
								<div class="col-auto">
									<i class="fas fa-book fa-2x text-gray-300"></i>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--Bloco de repetição-->

				<!--Bloco de repetição-->
				<div onclick="window.location='/questionario2'" class="col-xl-3 col-md-6 mb-4 pointer">
					<div class="card border-left-primary shadow h-100 py-2  col-md-11">
						<div class="card-body p-2">
							<div class="row no-gutters align-items-center">
								<div class="col mr-2">
									<div class="h5 mb-0 font-weight-bold text-gray-800"></div>
									<p class="m-0">Exercicio-3</p>
								</div>
								<div class="col-auto">
									<i class="fas fa-book fa-2x text-gray-300"></i>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--Bloco de repetição-->

				<!--Bloco de repetição-->
				<div onclick="window.location='/questionario4'" class="col-xl-3 col-md-6 mb-4 pointer">
					<div class="card border-left-primary shadow h-100 py-2  col-md-11">
						<div class="card-body p-2">
							<div class="row no-gutters align-items-center">
								<div class="col mr-2">
									<div class="h5 mb-0 font-weight-bold text-gray-800"></div>
									<p class="m-0">Exercicio-4</p>
								</div>
								<div class="col-auto">
									<i class="fas fa-book fa-2x text-gray-300"></i>
								</div>
							</div>
						</div>
					</div>
				</div>





		</div>
</div>
