<h6><a class="text-info" href="/home">HOME/</a>CADASTRAR UM NOVO ALUNO</h6>
<hr>
<div class="container p-0">
	<div class="row col-md-12 bg-white p-2 rounded m-0">

		<form class="col-md-12" action="/insereAluno" method="post">
						<div class="row col-md-12">
								<div class="row col-md-5">
									<label class="mt-2" for="nome"><strong>Nome do aluno</strong></label>
									<input id="nome" type="text" class="form-control" name="nome">
								</div>

								<div class="row col-md-3 ml-3">
									<label class="mt-2" for="username"><strong>Username</strong></label>
									<input id="username" type="text" class="form-control" name="username">
								</div>

								<div class="row col-md-3 ml-3">
									<label class="mt-2" for="senha"><strong>Senha</strong></label>
									<input id="senha" type="text" class="form-control" name="senha">
								</div>
						</div>

						<div class="row col-md-4 mt-3">
							<label for="turma"><strong>Turma</strong></label>
							<select class="form-control " name="turma">
									<?php foreach ($this->view->turmas as $turma): ?>
									<option value="<?= $turma['id_turma'] ?>"><?= $turma['nomeTurma'] ?></option>
									<?php endforeach; ?>
							</select>
						</div>

						<div class="row col-md-12 justify-content-end">
							<button type="submit" class="btn btn-success">Cadastrar aluno</button>
						</div>

		</form>

	</div>
</div>
