
<style media="screen">
	img{
		border-radius: 50%;
	}
	#bar-top{
		border-top-left-radius: 10px;
		border-top-right-radius: 10px;
	}
</style>
<h6><a class="text-info" href="/turmaAlun?turma=<?= $_GET['turma'] ?>">Turma / </a> Edição dos dados da turma </h6>
<hr>
<div class="container p-3">

		<div id="bar-top" class="row col-md-12 bg-primary p-3 m-0 justify-content-end">

		</div>

		<div class="row col-md-12 bg-white p-2 m-0 rounded">



			<hr>
			<?php if($this->view->alunos != NULL): ?>
			<table class="table">
				<tr class="text-center">
					<td><strong>Img</strong></td>
					<td class="text-left"><strong>Nome</strong></td>
					<td><strong>Username</strong></td>
					<td><strong>Senha</strong></td>
					<td><strong>Telefone</strong></td>
				</tr>

				<?php
				     $i=1;
						 foreach ($this->view->alunos as $aluno):
				?>

				<tr class="text-center">
					<td>
						<img src="assets/dashboard/img/avatar/avatar.jpg" width="50px" height="50px">
					</td>
					<td style="vertical-align:middle; text-align:left;">
						<input type="text" class="form-control" name="" value="<?= $aluno['nome'] ?>">
					</td>
					<td style="vertical-align:middle;">
						<input class="form-control" type="text" name="" value="<?= $aluno['username'] ?>">
					</td>
					<td style="vertical-align:middle;">
						<input class="form-control" type="text" name="" value="<?= $aluno['senha'] ?>">
					</td>
					<td style="vertical-align:middle;">
						 <input class="form-control" type="text" name="" value="<?= $aluno['Telefone'] ?>">
					 </td>
				</tr>

				 <?php $i++; endforeach;?>
			</table>

		<?php else: ?>

							<div class="row col-12 justify-content-center d-flex mt-2">
							<h5>AINDA NÃO HÁ ALUNOS CADASTRADOS PARA ESTÁ TURMA</h5>
							</div>

		<?php endif; ?>
		</div>
</div>

<div class="modal fade" id="excluirModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header bg-danger text-white">
				<h5 class="modal-title" id="exampleModalLabel">Deseja realmente excluir este aluno(@)?</h5>
				<button class="close" type="button" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">Selecione a opção excluir caso queira realmente excluir o anluno(@).</div>
			<div class="modal-footer">
				<button class="btn btn-success" type="button" data-dismiss="modal" >Cancelar</button>
				<a class="btn btn-danger" href="/deleteAlun?id=<?= $aluno['id_aluno'].'&turma='.$aluno['turma'] ?>">Excluir</a>
			</div>
		</div>
	</div>
</div>




<div class="modal fade" id="InsertModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header bg-success text-white">
				<h5 class="modal-title" id="exampleModalLabel"> Inserir um novo aluno para a turma <?= $this->view->infoTurma['nomeTurma'] ?></h5>
				<button class="close" type="button" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
			</div>


			<div class="row col-12 p-3 m-0 ">
				<form class="col-12" action="/insereAluno" method="post">
					<label><strong>Nome do aluno</strong></label>
					<input class="form-control" type="text" name="nome">

					<label class="mb-0 mt-2"><strong>Telefone</strong></label>
					<input class="form-control" type="text" name="phone">

					<label class="mb-0 mt-3"><strong>Username</strong></label>
					<input class="form-control" type="text" name="username">

					<label class="mb-0 mt-3"><strong>Senha</strong></label>
					<input class="form-control" type="text" name="senha">
					<input type="hidden" name="turma" value="<?= $this->view->infoTurma['id_turma'] ?>">
					<input type="hidden" name="goBack" value="turmaAlun">
					<input type="hidden" name="parameter">
			</div>


			<div class="modal-footer bg-primary">
				<button class="btn btn-danger" type="button" data-dismiss="modal" >Cancelar</button>
				<button class="btn btn-success" type="submit"><a>Inserir</a></button>
				</form>
			</div>
		</div>
	</div>
</div>
