<?php foreach ($this->view->infoProfessor as $professor): ?>
<?php
	$nome = explode(' ',$professor['nome']);
?>

<style media="screen">
	#course{
		background: url("assets/dashboard/images/motherboard2.jpg");
	}
</style>

<div class="col-md-4">
    <section class="card">
        <div id="course" class="twt-feed blue-bg bg-info">

					<a href="/PerfilProfessor?cod=<?= $professor['id_professor'] ?>">
            <div class="corner-ribon black-ribon">
                <i class="ti-settings"></i>
            </div>
						</a>
            <div class="fa fa-desktop wtt-mark"></div>

            <div class="media">
                <a href="#">
                    <img class="align-self-center rounded-circle mr-3" style="width:85px; height:85px;" alt="" src="assets/dashboard/images/avatar/user.jpg">
                </a>
                <div class="media-body">
                    <h2 class="text-white display-6"><?= $nome[0] ?></h2>
                    <p class="text-light">Professor</p>
                </div>
            </div>



        </div>
        <div class="weather-category twt-category">
            <ul>
                <li class="active">
                    <h5><?= $professor['num'] ?></h5>
                    Turmas
                </li>
                <li>
                    <h5>0</h5>
                    Alunos
                </li>
                <li>
                    <h5>0</h5>
                    Horas aula
                </li>
            </ul>
        </div>


    </section>
</div>


<?php endforeach; ?>
