<h6><a class="text-info" href="/home">HOME/</a>CADASTRAR UM NOVO PROFESSOR </h6>
<hr>
<div class="container p-0">
		<div class="row col-md-12 p-2 bg-white m-0 rounded">
			<form class="col-12" action="/insereProfessor" method="post">

			<div class="row col-md-12 p-0 m-0">
				<div class="row col-md-5 mt-2 ">
					<label class="mb-0" for="nome"><strong>Nome do Professor</strong></label>
					<input id="nome" type="text" class="form-control" name="nome">
				</div>

				<div class="row col-md-3 mt-2  p-0 ml-5">
					<label class="mb-0" for="username"><strong>Username</strong></label>
					<input id="username" type="text" class="form-control" name="username">
				</div>

				<div class="row col-md-3 mt-2  p-0 ml-5">
					<label class="mb-0" for="senha"><strong>Senha</strong></label>
					<input id="senha" type="text" class="form-control" name="senha">
				</div>

			</div>

				<div class="row col-md-5">
					<label for="leciona"class="mt-3 mb-0"><strong>Curso lecionado</strong> </label>
					<select class="form-control" name="leciona">
						<?php foreach ($this->view->cursos as $curso): ?>
							<option value="<?= $curso['id_curso'] ?>"><?= $curso['nomeCurso'] ?></option>
							<?php endforeach; ?>
					</select>
				</div>

				<div class="row col-md-5">
					<label for="leciona"class="mt-3 mb-0"><strong>O curso informado acima tem subcategoria?</strong> </label>
					<select class="form-control" name="subcategoria">
							<option value="---">Não há subcategoria para este curso</option>
							<option value="T">Desenvolvimento tecnológico</option>
							<option value="D">Desenvolvimento pessoal</option>
							<option value="A">Administrativo</option>
					</select>
				</div>

				<div class="row col-md-12 justify-content-end">
					<button type="submit" class="btn btn-success">Cadastrar Professor</button>
				</div>
			</form>
		</div>
		<div class="row col-md-12 p-0 m-0">
			<div class="row col-md-12 bg-white p-3 m-0 mt-2">
				<div class="row col-12 justify-content-center">
						<h1>Professores cadastrados</h1>
				</div>

					<table class="table table-hover">
						<tr class="text-center bg-primary text-white mb-5">
							<td>Nome</td>
							<td>Curso</td>
							<td>Username</td>
							<td>Senha</td>
							<td>Editar</td>
							<td>Excluir</td>
						</tr>

						<?php foreach ($this->view->infoProfessores as $professor): ?>

						<tr class="text-center p-3">
							<td><?=  $professor['nome'] ?></td>
							<td><?=  $professor['nomeCurso'] ?></td>
							<td><?=  $professor['username'] ?></td>
							<td> ******  </td>
							<td> <i class="fa  fa-pencil-alt fa-lg"></i> </td>
							<td> <a data-toggle="modal" data-target="#excluirModal<?= $professor['id_professor'] ?>"  href="remover"> <i class="fa fa-trash"></i> </a></td>
						</tr>


					<div class="modal fade" id="excluirModal<?= $professor['id_professor'] ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
							<div class="modal-dialog" role="document">
								<div class="modal-content">
									<div class="modal-header bg-danger text-white">
										<h5 class="modal-title" id="exampleModalLabel">Deseja realmente excluir este professor(@)?</h5>
										<button class="close" type="button" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">×</span>
										</button>
									</div>
									<div class="modal-body">Selecione a opção excluir caso queira realmente excluir o professor(@).</div>
									<div class="modal-footer">
										<button class="btn btn-success" type="button" data-dismiss="modal" >Cancelar</button>
										<a class="btn btn-danger" href="/deleteProf?id_prof=<?=  $professor['id_professor']  ?>">Excluir</a>
									</div>
								</div>
							</div>
						</div>

						<?php endforeach; ?>
					</table>

			</div>
		</div>




</div>
