<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>Login Cebrac</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="assets/login/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet"  href="assets/login/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet"  href="assets/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet"  href="assets/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet"  href="assets/login/vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet"  href="assets/login/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet"  href="assets/login/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet"  href="assets/login/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet"  href="assets/login/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet"  href="assets/login/css/util.css">
	<link rel="stylesheet"  href="assets/login/css/main.css">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url(assets/login/images/bg-01.jpg);">
					<span class="login100-form-title-1">
						Portal do aluno cebrac
					</span>
				</div>

				<?php if(isset($_SESSION['error']) && $_SESSION['error']==true):?>
				<h6 class="text-danger text-center mt-3">senha ou username incorreto, por favor tente novamente!!</h6>
				<?php endif; unset($_SESSION['error']); ?>

				<form action="/validate" method="post" class="login100-form validate-form">
					<div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
						<span class="label-input100">Username</span>
						<input class="input100" type="text" name="username" placeholder="@username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-18" data-validate = "Password is required">
						<span class="label-input100">Senha</span>
						<input class="input100" type="password" name="senha" placeholder="************">
						<span class="focus-input100"></span>
					</div>
<!--
					<div style="border-bottom:none;" class="wrap-input100  m-b-18" >
						<span class="label-input100 mt-1">Curso</span>
						<select name="tipo" class="form-control input100 mt-3">
							<option value="acc">Assistente administrativo</option>
							<option value="mcc">Manutenção de celulares e computadores</option>
							<option value="info">Informatica</option>
							<option value="af">Assistente de Farmacia</option>
							<option value="pb">Profissional da beleza</option>
							<option value="ig">Inglês</option>
						</select>
					</div>
-->

					<div style="border-bottom:none;" class="wrap-input100  m-b-18" >
						<span class="label-input100 mt-1">tipo de user</span>
						<select name="tipo" class="form-control input100 mt-3">
							<option value="professor">Professor@</option>
							<option value="administrador">CRA</option>
						</select>
					</div>

					<div class="flex-sb-m w-full p-b-30">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
						<!--	<label class="label-checkbox100" for="ckb1">
								Lembrar senha
							</label>-->
						</div>

						<div>
							<!--<a href="#" class="txt1">
								Esqueceu a senha?
							</a>-->
						</div>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Entrar
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>

<!--===============================================================================================-->
	<script src="assets/login/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="assets/login/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="assets/login/vendor/bootstrap/js/popper.js"></script>
	<script src="assets/login/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="assets/login/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="assets/login/vendor/daterangepicker/moment.min.js"></script>
	<script src="assets/login/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="assets/login/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="assets/login/js/main.js"></script>

</body>
</html>
