<!DOCTYPE html>
<html lang="pt-br">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Painel aluno Cebrac</title>

  <!-- Custom fonts for this template-->
  <link href="assets/dashboard/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="assets/dashboard/css/sb-admin-2.min.css" rel="stylesheet">

  <!-- <style media="screen">
    #content{
      background: url('assets/login/images/agri2.jpg');
      background-size:1280px;
      filter: blur(0px);
    }
  </style> -->


</head>

<body id="page-top" class="sidebar-toggled">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
		<!--toggled-->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/home_adm">
        <div class="sidebar-brand-icon rotate-n-">
					<?php
					switch ($this->view->logo['sigla']) {
						case 'inf':
						case 'INF':
							$logo = 'inf.jpg';
							break;
						case 'adm':
						case 'ADM':
							$logo = 'adm.jpg';
							break;
						case 'fmc':
						case 'FMC':
							$logo = 'fmc.jpg';
							break;
						case 'hdw':
						case 'HDW':
							$logo = 'hdw.jpg';
							break;
						case 'eng':
						case 'ENG':
							$logo = 'eng.jpg';
							break;
						case 'mcc':
						case 'MCC':
							$logo = 'mcc.png';
							break;
						case 'gew':
						case 'GEW':
							$logo = 'gew.jpg';
							break;
						case 'mid':
						case 'MID':
							$logo = 'mid.jpg';
							break;
						case 'emp':
						case 'EMP':
							$logo = 'emp.jpg';
							break;
						case 'app':
						case 'APP':
							$logo = 'app.png';
							break;
						case 'pbb':
						case 'PBB':
							$logo = 'pbb.jpg';
							break;
						case 'cgm':
						case 'CGM':
							$logo = 'cgm.png';
							break;
						case 'rob':
						case 'ROB':
							$logo = 'rob.png';
							break;
						case 'vmk':
						case 'VMK':
							$logo = 'vmk.png';
							break;
						case 'cdd':
						case 'CDD':
							$logo = 'cdd.jpg';
							break;
						case 'mec':
						case 'MEC':
							$logo = 'mec.jpg';
							break;
						default:
							$logo = 'adm.jpg';
							break;
					}
					?>
					<img src="assets/dashboard/icones/logoCurso/<?= $logo ?>">
					<!--<i class="fas fa-laugh-wink"></i>-->

        </div>
        <div class="sidebar-brand-text mx-3"><h6>Portal Hypersinc</h6></div>
      </a>

      <!-- Divider -->
      <!--<hr class="sidebar-divider my-0">-->

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="#">
          <!--<i class="fas fa-ad "></i>-->
					<!--<i class="fas fa-desktop "></i>-->
          <!--<span>Informática-aplicada</span>-->
					<!--<span>Assistente administrativo</span>-->

				</a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        <!--Opções-->
      </div>

			<li onclick="window.location='/home_adm'" class="nav-item">
				<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
					<i class="fas fa-home "></i>
					<span>Inicio</span>
				</a>

			</li>


		<!--	<li class="nav-item">
				<a class="nav-link collapsed" href="/page_entregar">
					<i class="fas fa-hand-holding"></i>
					<span>Entregar trabalhos</span>
				</a>
			</li>
-->
      <!-- Nav Item - Pages Collapse Menu -->
      <li onclick="window.location='perfil_aluno'" class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-user "></i>
          <span>Perfil</span>
        </a>

				<!--
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
         <h6 class="collapse-header">Tipo:</h6>
            <a class="collapse-item" href="#">Aluno</a>
            <a class="collapse-item" href="/professor">Professor</a>
						<a class="collapse-item" href="/turmas">Turma</a>
						<a class="collapse-item" href="/curso">Curso</a>
          </div>
        </div>
			-->
      </li>


      <!-- Nav Item - Utilities Collapse Menu -->
			<?php if (!isset($this->view->url)): ?>


      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Trabalhos</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <!--<h6 class="collapse-header">opções:</h6>-->
            <a class="collapse-item" href="/ent_trab?sub=<?= $_GET['sub']  ?>">Entregues</a>
						<!--<a class="collapse-item" href="/trab_entregu">Entregues</a>-->
            <!--<a class="collapse-item" href="utilities-border.html">Corrigidos</a>
            <a class="collapse-item" href="utilities-animation.html">Animations</a>
            <a class="collapse-item" href="utilities-other.html">Other</a>-->
          </div>
        </div>
      </li>
			<?php endif; ?>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">

      </div>

      <!-- Nav Item - Pages Collapse Menu -->
			<!--
      <li class="nav-item active">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Paginas</span>
        </a>
        <div id="collapsePages" class="collapse hide" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Opções do portal:</h6>
            <a class="collapse-item" href="#">Minhas faltas</a>
              <a class="collapse-item" href="#">Criar atividades</a>
            <a class="collapse-item" href="#">Forgot Password</a>
          </div>
        </div>
      </li>
		-->
      <!-- Nav Item - Charts -->
      <!--<li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Relatórios</span></a>
      </li>-->
<!--

      <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li>
-->
      <!-- Divider -->
  <!--    <hr class="sidebar-divider d-none d-md-block">-->

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
					<div class="col-6">
							<h6 class="mt-2">Turma: <?= $this->view->cursoAlun['nomeTurma'] ?></h6>
					</div>

          <!-- Topbar Search -->
          <form class=" d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group d-none">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Procurar por..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Procurar por..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>

                <span class="badge badge-danger badge-counter">1+</span>
              </a>

              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Centro de alertas
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">Agosto 30, 2019</div>
                    <span class="font-weight-bold">Este é um exemplo de alerta</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Mostrar todos alertas</a>
              </div>
            </li>

            <!--Nav Item - Messages-->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>

                <span class="badge badge-danger badge-counter">1</span>
              </a>

              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                	Centro de mensagens
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div class="font-weight-bold">
                    <div class="text-truncate">Este é um exemplo de mensagem.</div>
                    <div class="small text-gray-500">Julia Keler · 58m</div>
                  </div>
                </a>


                <a class="dropdown-item text-center small text-gray-500" href="#">Ver todas mensagens</a>
              </div>
            </li>
            <?php

            if($this->view->qtd_xp==NULL){
            $xp = 0;
          }else{
            $xp = $this->view->qtd_xp;
          }

             ?>
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link" href="#">
                <i class="fas fa-coins text-warning  mr-3 fa-2x"></i><h5 class="text-info"><strong><?= $xp ?></strong></h5><h5 class="text-info ml-1">XP</h5>

              </a>

            </li>
            <div class="topbar-divider d-none d-sm-block"></div>


            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><?= $this->view->nome ?></span>
                <img class="img-profile rounded-circle" src="assets/dashboard/img/avatar/avatar.jpg">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="/perfil_aluno">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Perfil
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Configurações
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Atividades
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Sair
                </a>
              </div>
            </li>


          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">


					<?= $this->content() ?>


        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer style="background:#16414a;" class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span class="text-white">Copyright &copy; PORTAL CEBRAC <?= date('Y')  ?></span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Deseja realmente sair?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Selecione a opção sair abaixo para encerrar a sessão.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href="/logout">Sair</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="assets/dashboard/vendor/jquery/jquery.min.js"></script>
  <script src="assets/dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="assets/dashboard/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="assets/dashboard/js/sb-admin-2.min.js"></script>

</body>

</html>
